language: c
sudo: false
dist: trusty
addons:
  apt:
    packages:
      - libogg-dev
      - libspeexdsp-dev
      - libfftw3-dev

env:
  matrix:
    - CMAKE=1 CONFIG=""
    - CMAKE=1 CONFIG="-DENABLE_FIXED_POINT:BOOL=TRUE -DENABLE_FLOATING_POINT:BOOL=FALSE"
    - CMAKE=1 CONFIG="-DENABLE_FIXED_POINT:BOOL=TRUE -DENABLE_FLOATING_POINT:BOOL=FALSE -DDISABLE_FLOAT_API:BOOL=TRUE"
    - CMAKE=1 CONFIG="-DENABLE_VORBIS_PSY:BOOL=TRUE"
    - CMAKE=1 CONFIG="-DDISABLE_BINARIES:BOOL=TRUE"
    - AUTOTOOLS=1 CONFIG=""
    - AUTOTOOLS=1 CONFIG="--enable-fixed-point"
    - AUTOTOOLS=1 CONFIG="--enable-fixed-point --disable-float-api"
    - AUTOTOOLS=1 CONFIG="--enable-vorbis-psy"
    - AUTOTOOLS=1 CONFIG="--disable-binaries"

os:
  - linux
  - osx

compiler:
  - gcc
  - clang

before_install:
  - if [[ "${TRAVIS_OS_NAME}" == "osx" ]]; then
      brew install libogg speexdsp fftw;
    fi

script:
  - if [ "$CMAKE" == "1" ]; then mkdir cmake-build; cd cmake-build; cmake .. $CONFIG -DBUILD_SHARED_LIBS:BOOL=TRUE -DCMAKE_INSTALL_PREFIX:PATH=$HOME/cmake-check; make install; fi
  - if [ "$AUTOTOOLS" == "1" ]; then ./autogen.sh; ./configure $CONFIG; make distcheck; fi
