language: c

os:
  - linux
  - osx

compiler:
  - gcc
  - clang

env:
  - CONFIG=""
  - CONFIG="--enable-fixed-point"
  - CONFIG="--enable-fixed-point --disable-float-api"
  - CONFIG="--enable-vorbis-psy"
  - CONFIG="--disable-binaries"

script:
  - ./autogen.sh
  - ./configure $CONFIG
  - make distcheck
